### ISSUE TITLE
Prijava na bazo

### ISSUE THREAD

**Issue by jaanos** [RenkoT97/OrganizatorNakupov#2]
Vidim, da sta v e4985b49596b7afa49be4c89bd10ef41c862fa33 in 030a6117e3ee3dd4eb58e9201260d80d43112fe9 vključila svoji gesli za dostop na bazo, ki sta tako za vekomaj objavljeni na internetu. Tako svetujem, da @RenkoT97 in @zankastelic zamenjata svoji gesli, namesto tega naj se aplikacija na bazo prijavi kot uporabnik `javnost`, ki mu seveda dajta ustrezne pravice (glejta npr. pdurcik/Baza-clanstva-RDR#3).

**Comment by jaanos** [comment]
Opažam, da se sedaj aplikacija prijavi s podatki iz datoteke `conf_baza.py`, kjer imata svoji gesli - tako bosta lahko le sama pognala aplikacijo. Kot rečeno, poskrbita za to, da se bo aplikacija prijavila z uporabnikom `javnost` - najbolje bo, da naredite kopijo datoteke `conf_baza.py` s podatki za prijavo, ki pa naj bo vključena v repozitorij (tako bo omogočeno poganjanje aplikacije komurkoli).

Mimogrede, na repozitoriju je ostala datoteka `Baza/__pycache__/conf_baza.cpython-39.pyc` - gre za avtomatsko generirano datoteko s podatki iz `conf_baza.py`, ki tako vsebuje geslo za prijavo na bazo. Glede na to, da imata v `.gitignore` že vnos `*.pyc`, bo zadostovalo, če datoteko pobrišeta in naredita commit, potem pa vama je git ne bo več ponujal za vključitev v commite. Vidim pa, da v 71a077a384315e8f9bf2ebdfdfcb78efac4f5167 in c65cf2c747a119a1d0279c1ff7451642a6e27c50 datoteka razkriva gesli za bazo, tako da svetujem, da ga @zankastelic še enkrat zamenjaš.

**Comment by zankastelic** [comment]
Datoteko sem pobrisal ven. 
Sem naredil datoteko auth_public.py in dodal podatke za javnost, da bo imel vsak dostop. 
V datoteki postavitev_baze.py pa sem dodal pravice tjasar in javnosti. 

Vendar imam sedaj težavo: noče mi povezati z bazo. Javlja napako: 
psycopg2.OperationalError: FATAL:  permission denied for database "sem2021_zanka"
DETAIL:  User does not have CONNECT privilege.

**Comment by jaanos** [comment]
Kot rečeno, bo potrebno dati uporabniku `javnost` ustrezne pravice - glej povezavo v prvem komentarju.

**Comment by zankastelic** [comment]
Sem dodal vse pravice kot je opisano v povezavi v prvem komentarju, pa vendar še vedno ne dela in dobim error: 

InsufficientPrivilege('permission denied for relation kosarica\n')

**Comment by jaanos** [comment]
Kolikor vidim, sta uporabniku `javnost` dala le pravico branja (`SELECT`) na tabelah `kosarica`, `osebe`, `trgovine` (manjka še `izdelki`). Potrebno bo dodeliti še ostale potrebne pravice - kolikor vidim, trenutno potrebujete še `INSERT` na tabelah `kosarica` in `osebe`, torej
```sql
GRANT INSERT ON kosarica TO javnost;
GRANT INSERT ON osebe TO javnost;
```
Po potrebi lahko seveda to naredita še za ostale tabele in operacije (`UPDATE`, `DELETE`).

**Comment by zankastelic** [comment]
Najlepša hvala. Sedaj deluje in mislim, da so dodane vse potrebne pravice.
