### ISSUE TITLE
dodajanje v tabelo

### ISSUE THREAD

**Issue by zankastelic** [RenkoT97/OrganizatorNakupov#3]
Pozdravljeni, 

imava težavo: ne veva namreč kje je napaka v naslednjem ukazu 
(primer:) 
insert into osebe (uporabnisko_ime, geslo, ime, priimek) values ('bkleinsmuntz2r','nmUogy','Berta','Kleinsmuntz');

Lep pozdrav

**Comment by jaanos** [comment]
SQL stavek izgleda pravilno. Sklepam pa, da do napake pride zato, ker je v tabeli že vnos z istim uporabniškim imenom (ki je nastavljeno kot glavni ključ).

Mimogrede, svetujem, da namesto uporabniškega imena za glavni ključ raje uporabite nek ID tipa `SERIAL` - nanj naj gredo potem tudi reference iz drugih tabel. Stolpec `uporabnisko_ime` naj ima seveda določili `NOT NULL` in `UNIQUE`, da bo uporabniško ime še vedno obvezno in brez ponovitev. Tudi ID-ja v tabelah `trgovine` in `vsi_izdelki` (za slednjo bi bilo boljše ime kar `izdelki`) naj bosta tipa `SERIAL` (in ne `TEXT`).

**Comment by zankastelic** [comment]
Hvala, sva naredila tako.
